
		align	4
		label	L820_len__hla_ word
		dd	020h
		dd	020h
		label	L820_str__hla_ byte
		db	"Gimme a decimal value to print: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L842_len__hla_ word
		dd	015h
		dd	015h
		label	L842_str__hla_ byte
		db	"Number in binary is: "
		db	0

		db	0
		db	0

		align	4
		label	L860_len__hla_ word
		dd	01h
		dd	01h
		label	L860_str__hla_ byte
		db	"_"
		db	0

		db	0
		db	0
