
		align	4
		label	L819_len__hla_ word
		dd	0fh
		dd	0fh
		label	L819_str__hla_ byte
		db	" "
		db	09h
		db	"C     A   TTT"
		db	0


		align	4
		label	L837_len__hla_ word
		dd	0dh
		dd	0dh
		label	L837_str__hla_ byte
		db	" C   A  A   T"
		db	0

		db	0
		db	0

		align	4
		label	L855_len__hla_ word
		dd	09h
		dd	09h
		label	L855_str__hla_ byte
		db	" C,   AAA"
		db	0

		db	0
		db	0

		align	4
		label	L873_len__hla_ word
		dd	05h
		dd	05h
		label	L873_str__hla_ byte
		db	"  C, "
		db	0

		db	0
		db	0

		align	4
		label	L891_len__hla_ word
		dd	06h
		dd	06h
		label	L891_str__hla_ byte
		db	"    C,"
		db	0

		db	0
