
		align	4
		label	L820_len__hla_ word
		dd	043h
		dd	043h
		label	L820_str__hla_ byte
		db	"Please enter a number or letters to have you Smc Fee's calculated: "
		db	0


		align	4
		label	L845_len__hla_ word
		dd	0dh
		dd	0dh
		label	L845_str__hla_ byte
		db	"Fall Semester"
		db	0

		db	0
		db	0

		align	4
		label	L865_len__hla_ word
		dd	0fh
		dd	0fh
		label	L865_str__hla_ byte
		db	"Spring Semester"
		db	0


		align	4
		label	L883_len__hla_ word
		dd	0ah
		dd	0ah
		label	L883_str__hla_ byte
		db	"No parking"
		db	0

		db	0

		align	4
		label	L902_len__hla_ word
		dd	07h
		dd	07h
		label	L902_str__hla_ byte
		db	"Parking"
		db	0


		align	4
		label	L921_len__hla_ word
		dd	0fh
		dd	0fh
		label	L921_str__hla_ byte
		db	"Winter Semester"
		db	0


		align	4
		label	L939_len__hla_ word
		dd	0ah
		dd	0ah
		label	L939_str__hla_ byte
		db	"No Parking"
		db	0

		db	0

		align	4
		label	L957_len__hla_ word
		dd	0fh
		dd	0fh
		label	L957_str__hla_ byte
		db	"Summer Semester"
		db	0


		align	4
		label	L1008_len__hla_ word
		dd	0ch
		dd	0ch
		label	L1008_str__hla_ byte
		db	"Non-Resident"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1027_len__hla_ word
		dd	0bh
		dd	0bh
		label	L1027_str__hla_ byte
		db	"CA Resident"
		db	0


		align	4
		label	L1046_len__hla_ word
		dd	06h
		dd	06h
		label	L1046_str__hla_ byte
		db	" units"
		db	0

		db	0

		align	4
		label	L1068_len__hla_ word
		dd	0eh
		dd	0eh
		label	L1068_str__hla_ byte
		db	"Total Fees = $"
		db	0

		db	0
