
		align	4
		label	L827_len__hla_ word
		dd	04ch
		dd	04ch
		label	L827_str__hla_ byte
		db	"Please enter some numbers to compute the area of a pyramid, cone, cylinder: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L845_len__hla_ word
		dd	0ch
		dd	0ch
		label	L845_str__hla_ byte
		db	"Enter an r: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L867_len__hla_ word
		dd	0ch
		dd	0ch
		label	L867_str__hla_ byte
		db	"Enter an b: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L889_len__hla_ word
		dd	0ch
		dd	0ch
		label	L889_str__hla_ byte
		db	"Enter an h: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L911_len__hla_ word
		dd	011h
		dd	011h
		label	L911_str__hla_ byte
		db	"Pyramid, Sum_00: "
		db	0

		db	0
		db	0

		align	4
		label	L935_len__hla_ word
		dd	0eh
		dd	0eh
		label	L935_str__hla_ byte
		db	"Cone, Sum_01: "
		db	0

		db	0

		align	4
		label	L959_len__hla_ word
		dd	012h
		dd	012h
		label	L959_str__hla_ byte
		db	"Cylinder, Sum_02: "
		db	0

		db	0

		align	4
		label	L987_len__hla_ word
		dd	04h
		dd	04h
		label	L987_str__hla_ byte
		db	" r= "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1002_len__hla_ word
		dd	04h
		dd	04h
		label	L1002_str__hla_ byte
		db	" b= "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1017_len__hla_ word
		dd	04h
		dd	04h
		label	L1017_str__hla_ byte
		db	" h= "
		db	0

		db	0
		db	0
		db	0
