
		align	4
		label	L838_len__hla_ word
		dd	015h
		dd	015h
		label	L838_str__hla_ byte
		db	" is the middle number"
		db	0

		db	0
		db	0

		align	4
		label	L956_len__hla_ word
		dd	017h
		dd	017h
		label	L956_str__hla_ byte
		db	" x, y, z are all equal "
		db	0


		align	4
		label	L970_len__hla_ word
		dd	019h
		dd	019h
		label	L970_str__hla_ byte
		db	"There is no middle number"
		db	0

		db	0
		db	0

		align	4
		label	L984_len__hla_ word
		dd	015h
		dd	015h
		label	L984_str__hla_ byte
		db	"Gimme a value for x: "
		db	0

		db	0
		db	0

		align	4
		label	L1006_len__hla_ word
		dd	015h
		dd	015h
		label	L1006_str__hla_ byte
		db	"Gimme a value for y: "
		db	0

		db	0
		db	0

		align	4
		label	L1028_len__hla_ word
		dd	015h
		dd	015h
		label	L1028_str__hla_ byte
		db	"Gimme a value for z: "
		db	0

		db	0
		db	0

		align	4
		label	L1050_len__hla_ word
		dd	05h
		dd	05h
		label	L1050_str__hla_ byte
		db	"AL = "
		db	0

		db	0
		db	0
