		label	L807_dReturnAddress__hla_ dword
		rb	4
		label	L808_wDIRegister__hla_ word
		dw 	00h
		label	L809_wDXRegister__hla_ word
		dw 	00h
		label	L810_dEAXRegister__hla_ dword
		dd	00h
		label	L811_dEBXRegister__hla_ dword
		dd	00h
		label	L812_dECXRegister__hla_ dword
		dd	00h
		label	L813_sData__hla_ dword
		rb	4
		label	L817_dReturnAddress__hla_ dword
		rb	4
		label	L818_wDXRegister__hla_ word
		dw 	00h
		label	L819_dEBXRegister__hla_ dword
		dd	00h
		label	L822_stringData__hla_ dword
		rb	4
		label	L823_i__hla_ dword
		dd	00h
		label	L824_count__hla_ dword
		dd	00h
		label	L826_dReturnAddress__hla_ dword
		rb	4
		label	L827_temp__hla_ dword
		rb	4
		label	L828_letter__hla_ dword
		rb	4
