
		align	4
		label	L846_len__hla_ word
		dd	0fh
		dd	0fh
		label	L846_str__hla_ byte
		db	"Pyramid, area: "
		db	0


		align	4
		label	L870_len__hla_ word
		dd	0ch
		dd	0ch
		label	L870_str__hla_ byte
		db	"Cone, area: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L894_len__hla_ word
		dd	010h
		dd	010h
		label	L894_str__hla_ byte
		db	"Cylinder, area: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L922_len__hla_ word
		dd	04ch
		dd	04ch
		label	L922_str__hla_ byte
		db	"Please enter some numbers to compute the area of a pyramid, cone, cylinder: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L940_len__hla_ word
		dd	0ch
		dd	0ch
		label	L940_str__hla_ byte
		db	"Enter an r: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L962_len__hla_ word
		dd	0ch
		dd	0ch
		label	L962_str__hla_ byte
		db	"Enter an b: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L984_len__hla_ word
		dd	0ch
		dd	0ch
		label	L984_str__hla_ byte
		db	"Enter an h: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1082_len__hla_ word
		dd	04h
		dd	04h
		label	L1082_str__hla_ byte
		db	" r= "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1097_len__hla_ word
		dd	04h
		dd	04h
		label	L1097_str__hla_ byte
		db	" b= "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1112_len__hla_ word
		dd	04h
		dd	04h
		label	L1112_str__hla_ byte
		db	" h= "
		db	0

		db	0
		db	0
		db	0
