
		align	4
		label	L828_len__hla_ word
		dd	04ch
		dd	04ch
		label	L828_str__hla_ byte
		db	"Please enter some numbers to compute the area of a pyramid, cone, cylinder: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L846_len__hla_ word
		dd	0ch
		dd	0ch
		label	L846_str__hla_ byte
		db	"Enter an r: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L868_len__hla_ word
		dd	0ch
		dd	0ch
		label	L868_str__hla_ byte
		db	"Enter an b: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L890_len__hla_ word
		dd	0ch
		dd	0ch
		label	L890_str__hla_ byte
		db	"Enter an h: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L927_len__hla_ word
		dd	0fh
		dd	0fh
		label	L927_str__hla_ byte
		db	"Pyramid, area: "
		db	0


		align	4
		label	L951_len__hla_ word
		dd	0ch
		dd	0ch
		label	L951_str__hla_ byte
		db	"Cone, area: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L975_len__hla_ word
		dd	010h
		dd	010h
		label	L975_str__hla_ byte
		db	"Cylinder, area: "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1003_len__hla_ word
		dd	04h
		dd	04h
		label	L1003_str__hla_ byte
		db	" r= "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1018_len__hla_ word
		dd	04h
		dd	04h
		label	L1018_str__hla_ byte
		db	" b= "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L1033_len__hla_ word
		dd	04h
		dd	04h
		label	L1033_str__hla_ byte
		db	" h= "
		db	0

		db	0
		db	0
		db	0
