
		align	4
		label	L838_len__hla_ word
		dd	011h
		dd	011h
		label	L838_str__hla_ byte
		db	" is in the middle"
		db	0

		db	0
		db	0

		align	4
		label	L956_len__hla_ word
		dd	01ch
		dd	01ch
		label	L956_str__hla_ byte
		db	"X and Y and Z are all equal!"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L970_len__hla_ word
		dd	010h
		dd	010h
		label	L970_str__hla_ byte
		db	"No middle Number"
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L984_len__hla_ word
		dd	0bh
		dd	0bh
		label	L984_str__hla_ byte
		db	"Feed Me X: "
		db	0


		align	4
		label	L1006_len__hla_ word
		dd	0bh
		dd	0bh
		label	L1006_str__hla_ byte
		db	"Feed Me Y: "
		db	0


		align	4
		label	L1028_len__hla_ word
		dd	0bh
		dd	0bh
		label	L1028_str__hla_ byte
		db	"Feed Me Z: "
		db	0


		align	4
		label	L1050_len__hla_ word
		dd	05h
		dd	05h
		label	L1050_str__hla_ byte
		db	"AL = "
		db	0

		db	0
		db	0
